### ISSUE TITLE
Undeferred field is not shown

### ISSUE THREAD

**Issue by BakaKami** [felipe-gdr/spring-graphql-defer#5]
When I tried to run your code, both the `author` in book1 and book2 got incrementally delivered. This is expected behaviour. But what I do not understand is why the field `name` which is not deferred in book1, not getting queried at the first place.

**Comment by rstoyanchev** [comment]
It's not clear what you mean by "not getting queried". It is in the response for the first part:

```
[main]$ curl -v http://localhost:8080/graphql -H "Content-Type:application/json" --data \
'{"query": "query bookTestSimple { bookById(id: \"book-1\") { name ... @defer { author { firstName } } } ... @defer { book2: bookById(id: \"book-2\") { name } } }"}'

* ...
> POST /graphql HTTP/1.1
> Host: localhost:8080
> ...
> 
< HTTP/1.1 200 OK
< content-type: multipart/mixed; boundary="-"
< ...
< 

content-type: application/json; charset=utf-8

{"data":{"bookById":{"name":"Effective Java"}},"hasNext":true}
---
content-type: application/json; charset=utf-8

{"hasNext":true,"incremental":[{"path":["bookById"],"data":{"author":{"firstName":"Joshua"}}}]}
---
content-type: application/json; charset=utf-8

{"hasNext":false,"incremental":[{"path":[],"data":{"book2":{"name":"Hitchhiker's Guide to the Galaxy"}}}]}
-----
```

**Comment by BakaKami** [comment]
ok. I think the issue is on the client side because I'm using altair for testing.

**Comment by imolorhe** [comment]
Hey! Creator of Altair GraphQL here 👋🏾 Stumbled on this issue randomly. If I may, the issue here is with the response from the server. Based on the [multipart content type](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) spec, any text that appears before the first boundary appears in the response is considered a _preamble_ and it gets ignored.

In your output above, you omitted the `---` boundary _before_ the first chunk output, so based on the spec, that is considered as a preamble and gets ignored, so only the second and third chunks are actually considered as the parts.

Altair uses [meros](https://github.com/maraisr/meros) to handle proper parsing of multipart responses and it does a great job of _doing the right thing_. So there is a bug [here](https://github.com/felipe-gdr/spring-graphql-defer/blob/main/src/main/java/org/example/springgraphqldefer/ExtendedGraphQlHttpHandler.java#L44C20-L44C34) in the code since you don't add the boundary _before_ iterating and encoding the results using `encodeResultMap`.

You can always use [Altair](https://altairgraphql.dev/) to easily verify your implementation works as expected 😊

**Comment by BakaKami** [comment]
@imolorhe hey, thanks for your response. So, the boundary has to be placed before all the data you want to consume right?
@rstoyanchev @felipe-gdr can you fix it?

**Comment by imolorhe** [comment]
Yes it does

**Comment by felipe-gdr** [comment]
Thanks for raising this.

Here's the fix: https://github.com/felipe-gdr/spring-graphql-defer/pull/6

**Comment by imolorhe** [comment]
you can always use Altair to test.
